# Generated by Django 6.0.6 on 2026-06-19 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('numclasse', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('matr_eleve', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom_ele', models.CharField(max_length=100)),
                ('pren_ele', models.CharField(max_length=100)),
                ('tel_ele', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse_ele', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('numoption', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tuteur',
            fields=[
                ('numtuteur', models.AutoField(primary_key=True, serialize=False)),
                ('nom_tuteur', models.CharField(max_length=100)),
                ('sexe_tuteur', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('tel_tuteur', models.CharField(max_length=20)),
                ('adresse_tuteur', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('numinscription', models.AutoField(primary_key=True, serialize=False)),
                ('date_inscr', models.DateField(auto_now_add=True)),
                ('matr_eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='inscription.eleve')),
                ('num_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='inscription.classe')),
                ('num_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='inscription.option')),
            ],
        ),
        migrations.AddField(
            model_name='eleve',
            name='numtuteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleves', to='inscription.tuteur'),
        ),
    ]
